apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character
  template:
    metadata:
      labels:
        app: character
    spec:
      containers:
        - name: character
          image: 425409/characterservice:main